Add some missing steps, update yarn build
klinker-apps/messenger-desktop pull request #7
Opened 2020-01-08 02:06 UTC by csm10495

Add some steps that you need before running yarn. Also update yarn build to get further with Windows and Linux

2020-01-08 02:07 UTC, csm10495 commented on package.json
> +    "build": "tsc && (cp -r src/assets built/assets || copy /b src/asserts built/assets)",
With ref to https://github.com/klinker-apps/pulse-sms-issues/issues/949

2020-01-08 02:09 UTC, csm10495 commented
Hmm, even after this i hit this weird error: 

![image](https://user-images.githubusercontent.com/5749838/71944512-d48bf500-3178-11ea-82ab-e1d4e566608c.png)

Seems like tsc is adding a character to the end of decrypt.js... any idea on that?

2020-01-08 02:23 UTC, klinker24 commented
Sorry, I am not really sure. I just tried it on my Windows computer, cleaned out my node modules and everything, I did not see any build issues. `yarn start` worked correctly on my end. Seems like something with your typescript if it isn't working.

2020-01-08 02:57 UTC, csm10495 commented
@klinker24 , got it. Latest worked for me completely. Something about the copy args being off (but me not noticing), seems to be what was leading to the character being added. Please check what we have now.

2020-01-08 02:58 UTC, csm10495 commented on package.json
> +    "typescript": "3.7.4"
I think this can be reverted back. Was from debug

2020-01-08 12:54 UTC, klinker24 approved these changes

2020-01-08 12:56 UTC, klinker24 requested changes

2020-01-08 12:56 UTC, klinker24 commented on README.md
> +1. Install Electron, Yarn, Typescript, and project dependencies:
Actually, let's update this comment.

```suggestion
1. Use Yarn as the package manager:
```

2020-01-08 22:35 UTC, csm10495 commented
I think I've made the requested change.

2020-01-09 02:35 UTC, klinker24 approved these changes

2020-01-09 02:35 UTC, merged